### PR TITLE
Update tools section in readme.md

### PR DESCRIPTION
**Pull request by MatofSteel1**
**Summary of changes:**
1. Added Git as a required tool because GenerateSolutions.bat runs Git commands.
2. Added instruction to install the "Desktop Development with C++" workload.

### CODE REVIEW

**Comment by Alistar031** [comment]
کارگزاران نور 
گاد بازی

**Comment by Alistar031** [comment]
عشق کیهانی

**Comment by Alistar031** [comment]
دروازه ی هشتم

**Comment by Alistar031** [comment]
کلید آزادی

**Comment by Alistar031** [comment]
بمب اتم کیهانی

**Comment by rys** [comment]
Fixed internally and will be included in an upcoming release. Will close when that's out, thanks!

**Comment by rys** [comment]
Thanks @MatofSteel1, fixed in a21ffb8!

**Pull request closed without merging**
